### ISSUE TITLE
🐛 Bug when adding / Editing participants

### ISSUE THREAD

**Issue by pedrojreis** [SyluxDX/daily-timer#2]
If we have n participants, run some dailies (I imagine to populate the stats) and then alter/add someone we get an error when launching the app.

![image](https://user-images.githubusercontent.com/28795057/222116777-45c38881-a808-42d7-a5b9-d0a43180c942.png)

Being "Eu" the new participant

**Comment by SyluxDX** [comment]
Bug fixed in new release [3.1](https://github.com/SyluxDX/daily-timer/releases/tag/v3.1)
The problem has the script used the member list obtained from the statistic file, instead of the list provided by the configuration json.
